const fallbackPublications = [
  {
    id: 0,
    title: "Learning collective behavior from data",
    authors: "C. Esparza-López, G. Stephens",
    journal: "In preparation",
    volume: "",
    page: "",
    year: "2024",
    link: "",
    keywords: ["machine learning", "collective behavior", "diffusion maps"],
  },
  {
    id: 1,
    title: "Rate invariance and scallop theorem in viscosity gradients",
    authors: "C. Esparza-López, E. Lauga",
    journal: "Phys. Rev. Fluids",
    volume: "8",
    page: "063301",
    year: "2023",
    link: "https://www.damtp.cam.ac.uk/user/lauga/papers/217.pdf",
    keywords: [
      "scallop theorem",
      "low-Reynolds number",
      "viscosity gradients",
      "reciprocal locomotion",
      "swimming microorganisms",
    ],
  },
  {
    id: 2,
    title: "Dynamics of a helical swimmer crossing viscosity gradients",
    authors:
      "C. Esparza-López, J. Gonzalez-Gutierrez, F. Solorio-Ordaz, E. Lauga, R. Zenit",
    journal: "Phys. Rev. Fluids",
    volume: "6",
    page: "083102",
    year: "2021",
    link: "https://arxiv.org/pdf/2012.04788",
    keywords: [
      "low-Reynolds number",
      "viscosity gradients",
      "artificial swimmers",
      "swimming bacteria",
      "resistive force theory",
    ],
  },
  {
    id: 3,
    title: "Hydrodynamic model for Spiroplasma motility",
    authors: "C. Esparza-López, E. Lauga",
    journal: "Phys. Rev. Fluids",
    volume: "5",
    issue: "9",
    page: "093102",
    year: "2020",
    link: "https://www.damtp.cam.ac.uk/user/lauga/papers/181.pdf",
    keywords: [
      "Spiroplasma",
      "swimming bacteria",
      "hydrodynamics",
      "low-Reynolds number",
      "resistive force theory",
    ],
  },
  {
    id: 4,
    title: "A stochastic model for bacteria-driven micro-swimmers",
    authors: "C. Esparza-López, A. Théry, E. Lauga",
    journal: "Soft Matter",
    volume: "15",
    issue: "12",
    page: "2605-2616",
    year: "2019",
    link: "https://www.damtp.cam.ac.uk/user/lauga/papers/158.pdf",
    keywords: [
      "bacteria-driven microswimmers",
      "random walks",
      "run-and-tumble",
      "hydrodynamics",
      "microrobotics",
      "active matter",
      "swimming bacteria",
    ],
  },
];

export default fallbackPublications;
